os: osx
osx_image: xcode12.4
language: swift
script: xcodebuild clean build test -project "/Users/Krishna/Projects/Essential Developer/EssentialFeed/EssentialFeed.xcodeproj" -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
